task:
  trigger_type: manual
  container:
    image: openjdk:8-jdk
  test_script: java -version

task:
    macos_instance:
      matrix:
        - image: big-sur-xcode-12.3
        - image: catalina-xcode-12.2
        
    test_script: ls $CIRRUS_WORKING_DIR
    setup_script:
      # Ffmpeg is only required for testing
      - brew install ffmpeg
      - git clone https://github.com/webcamoid/akvirtualcamera.git
      - mkdir akvirtualcamera/build
      - cd akvirtualcamera/build
      - cmake  -DCMAKE_BUILD_TYPE=Release .. 
      - cmake --build .
      # TODO Grab output from below command and use that instead of hardcoded AkVCamVideoDevice0
      - ./Manager/AkVCamManager add-device TestDevice
      - ./Manager/AkVCamManager add-format AkVCamVideoDevice0 RGB24 640 480 30
      - ./Manager/AkVCamManager update
      - ffmpeg -f avfoundation -list_devices true -i "" || true
      - brew install coreutils
      - timeout 5s ffmpeg -f avfoundation -i "0" --frames 1 capture.jpg
    image_artifacts:
      path: ./akvirtualcamera/build/capture.jpg
      
    

task:
  trigger_type: manual
  windows_container:
    image: cirrusci/windowsservercore:2019
  # Must be done in one script otherwise the PATH variable is lost.
  build_script: 
    - choco install -y openjdk8jre
    - refreshenv
    - java -version
