task:
  container:
    image: openjdk:8-jdk
  test_script: java -version

task:
    macos_instance:
      image: big-sur-xcode-12.3
    test_script: java -version

task:
  windows_container:
    image: cirrusci/windowsservercore:2019
  # Must be done in one script otherwise the PATH variable is lost.
  build_script: 
    - choco install -y openjdk8jre
    - refreshenv
    - java -version
