task:
  windows_container:
    image: cirrusci/windowsservercore:2019
  install_script: 
    - choco install -y openjdk8jre
    - refreshenv
    - set
    - echo "%PATH%"
    - java -version
  printenv_script: set
  test_script: java -version
